Only retrieve the pages that are registered in the settings
torchbox/wagtail-grapple pull request #226
Opened 2022-04-10 08:10 UTC by jffr

A small fix for removing pages that are not registered in the GRAPPLE settings.

Having a project with two apps (for example home and blog). You'll get an error when we only expose the 'blog' app. Which returns the following output:

```json
{
  "errors": [
    {
      "message": "Expected value of type \"Page\" but got: HomePage.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": null
}
```

Where we have the following settings:

```python
INSTALLED_APPS = [
    'home',
    'search',
    'blog',
    ....
]

GRAPPLE = {
    "APPS": ["blog"],
    "EXPOSE_GRAPHIQL": True
}
```

And the query:

```graphql
{
  pages {
    id
    title
    pageType
    slug
  }
}
```

2022-04-10 08:13 UTC, zerolab commented
Hey @jffr, thank you for this. 
Could you add a test for the changes, please?

2022-04-10 09:22 UTC, jffr commented
@zerolab Thank you for the feedback! I have fixed the failing tests and introduced two new tests for the app setting:
* Getting no pages when there no apps are configured;
* Getting all the (home related) pages when the app 'home' is configured;

I think we're missing one last test, which is a query where we get more pages from different apps. But in order to write that test we have to include a new demo app within the example project. Do you think it is worth it or are the test cases explained above good enough?

2022-04-21 13:53 UTC, zerolab requested changes
Hey @jffr,

thank you for this. left a few notes/suggestions

2022-04-24 08:01 UTC, jffr commented on example/example/tests/test_grapple.py
> +        self.assertEquals(pages_data[1]["contentType"], "home.BlogPage")
Thank you for the feedback. I've been trying to add a new app, but it somehow never gets detected by Graphene. Do you by know how to fix this?

<img width="1012" alt="Screenshot 2022-04-24 at 09 59 34" src="https://user-images.githubusercontent.com/74216106/164966394-5309ea37-8c2e-4287-9217-0357ee135c38.png">

I have created a factory and a new test case:

```python
class BaseGrappleTest(TestCase):
    def setUp(self):
        self.client = Client(SCHEMA, middleware=MIDDLEWARE)
        self.home = HomePage.objects.first()


class PagesTest(BaseGrappleTest):
    def setUp(self):
        super().setUp()
        self.factory = RequestFactory()
        self.blog_post = BlogPageFactory(parent=self.home)
        self.news_post = NewsPageFactory(parent=self.home)

    def test_pages_with_news_app(self):
        query = """
        {
            pages {
                id
                title
                contentType
            }
        }
        """

        executed = self.client.execute(query)

        print(executed)
```

2022-04-24 08:18 UTC, jffr commented on example/example/tests/test_grapple.py
> +        self.assertEquals(pages_data[1]["contentType"], "home.BlogPage")
Thank you for the feedback. I have created a new app to test if everything is working accordingly.

2022-04-24 16:43 UTC, zerolab commented on example/example/tests/test_grapple.py
> +        self.assertEquals(pages_data[1]["contentType"], "home.BlogPage")
I suggest adding `news_post = NewsPageFactory(parent=self.home)` before the execute and add a check to ensure the news page doesn't appear in the results

2022-04-24 16:45 UTC, zerolab commented on example/home/migrations/0023_alter_blogpage_body.py
> +# Generated by Django 3.2.13 on 2022-04-24 07:18
I can't see the changes that triggered this migration 🤔

2023-05-12 02:32 UTC, dopry commented
@jffr do you still have any inclination to work on this PR?

2025-01-09 05:31 UTC, closed without merging