Feature/wagtail 3 support
torchbox/wagtail-grapple pull request #229
Opened 2022-05-26 08:12 UTC by fabienheureux

2022-06-05 15:37 UTC, zerolab commented on .github/workflows/ci.yml
> +        wagtail-version: ['2.14', '2.15', '2.16', '3.0']
let's drop support for Wagtail < 2.15

2022-06-05 15:43 UTC, zerolab requested changes
Lot of good stuff, @fabienheureux 
Thank you for this. And sorry it took so long to follow up.

A few changes and we should be good to go

2022-06-05 15:43 UTC, zerolab commented on example/home/models.py
> +try:
nitpic: I'd prefer a more explicit conditional usage in the panel definitions (i.e. `FieldPanel() if WAGTAIL_VERSION >= (3, 0) else StreamFieldPanel`

2022-06-05 15:43 UTC, zerolab commented on requirements.txt
> +wagtail>=2.14,<4.0
```suggestion
wagtail>=2.15,<4.0
```

2022-06-05 15:43 UTC, zerolab commented on setup.cfg
> +    wagtail>=2.14, <4.0
```suggestion
    wagtail>=2.15, <4.0
```

2022-06-07 08:46 UTC, fabienheureux commented
Hey @zerolab , thanks for the review !
I have updated the PR according to your feedback, let me know if it requires more changes.

2022-06-07 09:10 UTC, zerolab approved these changes
LGTM. Thank you @fabienheureux

2022-06-07 09:11 UTC, merged